xir5-37-HotelSantai/Controllers/KamarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using xir5_37_HotelSantai.Models.EntityManager;
using xir5_37_HotelSantai.Models.ViewModel;

namespace xir5_37_HotelSantai.Controllers
{
    public class KamarController : Controller
    {
        // GET: Kamar
        public ActionResult AddKamar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddKamar(KamarView kv)
        {
            if (ModelState.IsValid)
            {
                KamarManager KM = new KamarManager();
                KM.AddKamar(kv);
                return RedirectToAction("Welcome", "Home");
            }
            return View();
        }
        public ActionResult ManageKamarPartial(string status = "")
        {
            //if (User.Identity.IsAuthenticated)
            //{
            string loginName = User.Identity.Name;
            KamarManager KM = new KamarManager();
            KamarDataView KDV = new KamarDataView();
            KDV.KamarProfile = KM.GetKamarData();
            string message = string.Empty;
            if (status.Equals("update"))
                message = "Update Successful";
            else if (status.Equals("delete"))
                message = "Delete Successful";
            ViewBag.Message = message;
            return PartialView(KDV);
            //}
            // return RedirectToAction("Index", "Home");
        }
        public ActionResult UpdateKamarData(int kamarID,int customerID, string noKamar, string
       namaKamar, DateTime tanggal)
        {
            KamarView KV = new KamarView();
            KV.id_kamar = kamarID;
            KV.id_customer = customerID;
            KV.nama_kamar = namaKamar;
            KV.no_kamar = noKamar;
            KV.tanggal = tanggal;
            KamarManager KM = new KamarManager();
            KM.UpdateKamar(KV);
            return Json(new { success = true });
        }
        public ActionResult DeleteKamar(int kamarID)
        {
            KamarManager KM = new KamarManager();
            KM.DeleteKamar(kamarID);
            return Json(new { success = true });
        }
        public ActionResult Perubahan()
        {
            return View();
        }
    }
}

xir5-37-HotelSantai/Views/Kamar/ManageKamarPartial.cshtml
@model xir5_37_HotelSantai.Models.ViewModel.KamarDataView
<div>
    <h1>List of Users</h1>
    <table class="table table-striped table-condensed table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>ID Customer</th>
                <th>Nama Kamar</th>
                <th>No Kamar</th>
                <th>Tanggal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var i in Model.KamarProfile)
            {
                <tr>
                    <td> @Html.DisplayFor(m => i.id_kamar)</td>
                    <td> @Html.DisplayFor(m => i.id_customer)</td>
                    <td> @Html.DisplayFor(m => i.nama_kamar)</td>
                    <td> @Html.DisplayFor(m => i.no_kamar)</td>
                    <td> @Html.DisplayFor(m => i.tanggal)</td>
                    <td><a href="javascript:void(0)" class="lnkEdit">Edit</a></td>
                    <td><a href="javascript:void(0)" class="lnkDelete">Delete</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div id="divEdit" style="display:none">
    <input type="hidden" id="hidID" />
    <table>
        <tr>
            <td>Id Customer</td>
            <td><input type="text" id="idcustomer" class="form-control" /></td>
        </tr>
        <tr>
            <td>Nama Kamar</td>
            <td><input type="text" id="txtNamaKamar" class="form-control" /></td>
        </tr>
        <tr>
            <td>No Kamar</td>
            <td><input type="text" id="txtNoKamar" class="form-control" /></td>
        </tr>
        <tr>
            <td>Tanggal</td>
            <td>
                @Html.TextBox("YourTextBox", "", new { id="tglpesan", @class = "datepicker"})
            </td>
        </tr>
        
    </table>
</div>
<script type="text/javascript">
 $(function () {
 var initDialog = function (type) {
 var title = type;
 $("#divEdit").dialog({
 autoOpen: false,
 modal: true,
 title: type + ' Kamar',
 width: 360,
 buttons: {
 Save: function () {
 var id = $("#hidID").val();
 var idcustomer = $("#idcustomer").val();
 var namaKamar = $("#txtNamaKamar").val();
 var nokamar = $("#txtNoKamar").val();
 var tanggal = $("#tglpesan").val();
 UpdateKamar(id, idcustomer,namaKamar,nokamar,tanggal);
$(this).dialog("destroy");
 },
Cancel: function () { $(this).dialog("destroy"); }
 }
 });
 }
 function UpdateKamar(id, idcstmr, nmkmr, nokmr, tgl) {
 $.ajax({
 type: "POST",
 url: "@(Url.Action("UpdateKamarData", "Kamar"))",
     data: { kamarID: id, idcustomer:idcstmr , namakamar: nama, nokamar: no,tanggal: tgl},
 success: function (data) {

$("#divUserListContainer").load("@(Url.Action("ManageKamarPartial","Kamar", new { status
="update" }))");
 },
 error: function (error) {
 //to do:
 }
 });
 }
 $("a.lnkEdit").on("click", function () {
 initDialog("Edit");
 $(".alert-success").empty();
 var row = $(this).closest('tr');
 $("#hidID").val(row.find("td:eq(0)").html().trim());
 $("#idcustomer").val(row.find("td:eq(1)").html().trim())
 $("#txtNamaKamar").val(row.find("td:eq(2)").html().trim())
 $("#txtNoKamar").val(row.find("td:eq(3)").html().trim())
 $("#divEdit").dialog("open");
 return false;
 });
 function DeleteKamar(id) {
 $.ajax({
 type: "POST",
 url: "@(Url.Action("DeleteKamar","Kamar"))",
 data: { kamarID: id },
 success: function (data) {

$("#divUserListContainer").load("@(Url.Action("ManageKamarPartial","Kamar", new { status
="delete" }))");
 },
 error: function (error) { }
 });
 }
$("a.lnkDelete").on("click", function () {
 var row = $(this).closest('tr');
 var id = row.find("td:eq(0)").html().trim();
 var answer = confirm("apakah anda yakin akan menghapus kamar dengan ID " + id + "?");
 if (answer)
 DeleteKamar(id);
 return false;
});
 });
</script>
<span class="alert-success">@ViewBag.Message</span>